# Generated by Django 2.1.2 on 2018-12-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='content',
            field=models.TextField(),
        ),
    ]
