# Generated by Django 2.1.2 on 2019-01-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_folderperm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderperm',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
