# Generated by Django 2.1.2 on 2019-01-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_auto_20190114_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.CharField(default='SYSTEM', max_length=256),
        ),
    ]
